# Generated by Django 4.0.1 on 2022-03-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=255)),
                ('itemcatagory', models.CharField(max_length=255)),
                ('itemquantity', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('approverstatus', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
